### ISSUE TITLE
How to test `listen`?

### ISSUE THREAD

**Issue by AkifumiSato** [oakserver/oak#153]
Promise is not resolved when you await with `listen()`.
But if you don't await, Deno's test warns you "leaking async ops"

Is there a way to test this?

deno 1.0.3
oak: 5.1.0

## code
```typescript
export const createApp = async (application: Application) => {
  const route = (new Router).routes()
  application.use(route)
  application.listen({ port: 8000 })
  console.log(`serve: http://localhost:${ port }/`) // await with `listen` doesn't reach here
}

Deno.test('createApp', async () => {
  const application = new Application()
  const spyListen = spy(application, 'listen')
  await createApp(application)

  assertEquals(spyListen.calls.length, 1)
  assertEquals(spyListen.calls[0].args[0], {
    port: 8000,
  })
})
```

## error
```
test createApp ... FAILED (1ms)

failures:

createApp
AssertionError: Test case is leaking async ops.
Before:
  - dispatched: 1
  - completed: 1
After:
  - dispatched: 3
  - completed: 2
```
