### ISSUE TITLE
cannot access server with docker-compose

### ISSUE THREAD

**Issue by carnival187** [oakserver/oak#375]
i'm trying to make my docker-compose.yml for my project, i reduced it to focus on my problem : 

```
version: "3.9"

services:
  aze:
    image: denoland/deno
    volumes:
      - .:/app
    entrypoint: deno run -A -r --unstable /app/src/try.ts
    ports:
      - 8000:8000
```
i noticed it work with a "simple" server without oak : 

```
import { serve } from "https://deno.land/std@0.103.0/http/server.ts"
const s = serve({ port: 8000 })
console.log("http://localhost:8000/")
for await (const req of s) {
  req.respond({ body: "Hello World\n" })
}
```
but it doen't when i use oak : 
```
import { Application, Router } from "https://deno.land/x/oak@v8.0.0/mod.ts"

const app = new Application()

const router = new Router()

router.get("/", ({ response }) => {
  console.log("TOUCHED")
  response.body = "hello"
})
app.use(router.routes())

app.listen("localhost:8000")
console.log("INIT")
```
i can't acess to it, "TOUCHED" is never log.

Did i miss something, am i doing something wrong ?

```Local deno version 1.12.2```
